### ISSUE TITLE
BUG: get error when trying to load stuff into filestore

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#94]
I got the following error running my tests:
```python
ERROR: __main__.test_pdfcalc_generated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/work-data/other_src/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/work-data/dev/simdb/simdb/tests/test_calc_storage.py", line 58, in test_pdfcalc_generated
    db_atoms = insert_atom_document('au2', atoms)
  File "/mnt/work-data/dev/simdb/simdb/utils/__init__.py", line 16, in inner
    return func(*args, **kwargs)
  File "/mnt/work-data/dev/simdb/simdb/insert.py", line 33, in insert_atom_document
    resource = insert_resource('ase', file_name)
  File "/mnt/work-data/other_src/filestore/filestore/api.py", line 180, in insert_resource
    return _FS_SINGLETON.insert_resource(spec, resource_path, resource_kwargs)
  File "/mnt/work-data/other_src/filestore/filestore/fs.py", line 224, in insert_resource
    col = self._resource_col
  File "/mnt/work-data/other_src/filestore/filestore/fs.py", line 161, in _resource_col
    self.__res_col = self._db.get_collection('resource')
  File "/mnt/work-data/other_src/filestore/filestore/fs.py", line 155, in _db
    self.__db = conn.get_database(self.config['database'])
  File "/mnt/work-data/other_src/anaconda/lib/python2.7/site-packages/pymongo/database.py", line 1050, in __call__
    self.__name, self.__connection.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'get_database' method on a 'MongoClient' object it is failing because no such method exists.
```

Do you know what I might be doing wrong?

**Comment by ericdill** [comment]
What version of pymongo, mongodb, mongod, mongo and mongoengine are you running. also what version of filestore

**Comment by CJ-Wright** [comment]
pymongo                   2.8                      py27_0    defaults
mongod --version : Tue Mar 29 14:24:32 git version: nogitversion
mongo --version : MongoDB shell version: 2.0.6
mongoengine               0.8.7                     <pip>
filestore (/mnt/work-data/other_src/filestore) 0.2.3+4.gc5ece37           <pip>
Working on mongodb version

**Comment by CJ-Wright** [comment]
Is it possible

**Comment by CJ-Wright** [comment]
Sorry wrong button

**Comment by ericdill** [comment]
Try pymongo 3+

**Comment by CJ-Wright** [comment]
That seems to have worked, although I now have an issue with my side of the code.
Thank you!

**Comment by ericdill** [comment]
Glad it's working :-D.  We should probably pin pymongo > 3 and mongoengine > some version in the conda-recipe. cc @tacaswell

**Comment by CJ-Wright** [comment]
Greater than 3 might be a problem, I was potentially having issues with 3.2. I don't know because it could have been caused by something else

**Comment by tacaswell** [comment]
Yes on pymongo.

Mongogenige is no longer a dep on master (sorry, oversite on my part with the deps).
